project:
  type: website
  output-dir: docs

website:
  title: "Barry Quinn CStat"
  navbar:
      right:
        - text: "Download PDF"
          href: index.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
exclude: 
  - "oldfiles/**"
  
editor: visual

