on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            - any::knitr
            - any::rmarkdown
            - any::dplyr
            - any::bib2df
            - any::tidyverse
            - any::kableExtra

      - name: Render Quarto Project
        run: |
          # Use our organized build system
          python3 scripts/build_cvs.py

      - name: Verify deployment files
        run: |
          echo "Files in dist directory:"
          ls -la dist/
          echo "Image directory contents:"
          ls -la dist/img/ || echo "No img directory found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist